name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: deploy the Docker image
      with:
        app-name: ${{ env.DEVWEBAPP }}
        publish-profile: ${{ secrets.DEV_DUP_WEBAPP }}
        images: 'nirulabs/tea:latest'
    - name: run command in container
    - run: 'httpd-foreground'
          
        
