name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Dev
    - uses: actions/deploy-docker@v1.0.1
      with:
        app-name: ${{ env.DEVWEBAPP }}
        publish-profile: ${{ secrets.DEV_DUP_WEBAPP }}
        images: 'nirulabs/tea:latest'
        containerCommand: httpd-foreground
          
        
