name: deploy a docker image to an Azure Web App

on:
  push:
    branches:
      - main
      - dev
      - prod
      - stage

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Deploy to development
      if: github.ref == 'refs/heads/dev'
      run: ./devwebapp.yaml
    - name: Deploy to stage
      if: github.ref == 'refs/heads/stage'
      run: ./stage_webapp.yaml
    - name: Deploy to stage
      if: github.ref == 'refs/heads/stage'
      run: ./prod_webapp.yaml
