name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
      - prod
      - dev
      - stage

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/prod'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: prod

    - name: Deploy to Prod
      run: |
       .github/workflows/deploytoprod

  deploy_to_dev:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/dev'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: dev
        
    - name: Deploy to Dev
      run: |
        ..github/workflows/deploytodev
      

  deploy_to_stage:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/stage'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: stage

    - name: Deploy to Stage
      run: |
        .github/workflows/deploytostage 
