name: Deploy to Azure App Service

on:
  push:
    branches:
      - prod
      - dev
      - stage

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-prodwebapp
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/prod' && github.repository == 'nikhatsultana639/deploydockerimage' }}
      uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
      with:
        app-name: ${{ env.PRODWEBAPP }}
        publish-profile: ${{ secrets.DEVNPRODWEBAPP }}
        images: 'nirulabs/tea:latest'
        package: .
        startup-command: 'httpd-foreground'  

  deploy_to_dev:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Dev
      id: deploy-to-devwebapp
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' && github.repository == 'nikhatsultana639/deploydockerimage' }}
      uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
      with:
        app-name: ${{ env.DEVWEBAPP }}
        publish-profile: ${{ secrets.DEV_DUP_WEBAPP }}
        images: 'nirulabs/tea:latest'
        package: .
        startup-command: 'httpd-foreground'

  deploy_to_stage:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-stagewebapp
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/stage' && github.repository == 'nikhatsultana639/deploydockerimage' }}
      uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
      with:
        app-name: ${{ env.STAGEWEBAPP }}
        publish-profile: ${{ secrets.STAGEWEBAPP }}
        images: 'nirulabs/tea:latest'
        package: .
        startup-command: 'httpd-foreground'
